# Generated by Django 4.0.2 on 2022-02-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_project_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
